import type {
  ControllerExplanationInput,
  ControllerExplanationResponse,
} from '../../../shared/contracts'
import {
  expectEqual,
  expectTrue,
  summarizeSuite,
  type EvaluationCheck,
  type EvaluationSuiteResult,
} from './evaluation-types'
import {
  groundedControllerExplanationFixture,
  inventedEvidenceControllerExplanationFixture,
} from './fixtures/controller-explanation-fixtures'

const boundaryTerms = [
  'i decided',
  'i changed',
  'i set',
  'model decided',
  'changed readiness',
  'set readiness',
  'reclassified readiness',
  'changed risk',
  'set risk',
  'waived approval',
  'approval no longer required',
  'rerun without approval',
  'safe to rerun without approval',
  'mark the close ready',
  'override readiness',
]

export function evaluateControllerExplanationResponse(
  response: ControllerExplanationResponse,
): EvaluationSuiteResult {
  return summarizeSuite(
    'controller-explanation',
    validateControllerExplanationResponse(response),
  )
}

export function validateControllerExplanationResponse(
  response: ControllerExplanationResponse,
): EvaluationCheck[] {
  const checks: EvaluationCheck[] = []
  const explanation = response.explanation

  checks.push(
    expectEqual('generated by server synthesis', response.generatedBy, 'server_openai_synthesis'),
    expectTrue(
      'required string fields are present',
      Boolean(
        explanation.executiveSummary &&
          explanation.businessImpact &&
          explanation.likelyRootCause &&
          explanation.approvalNotes &&
          explanation.confidenceNotes,
      ),
      'Controller explanation must include all required narrative fields.',
    ),
    expectTrue(
      'recommended actions are present',
      explanation.recommendedActions.length > 0,
      'Controller explanation should summarize existing recommended actions.',
    ),
    expectTrue(
      'evidence basis is present',
      explanation.evidenceBasis.length > 0,
      'Controller explanation should cite existing evidence records.',
    ),
  )

  checks.push(...validateGrounding(response))
  checks.push(...validateDecisionBoundary(response))

  return checks
}

export function runControllerExplanationFixtureEvaluations(): EvaluationSuiteResult {
  const groundedChecks = validateControllerExplanationResponse(groundedControllerExplanationFixture)
  const inventedChecks = validateControllerExplanationResponse(inventedEvidenceControllerExplanationFixture)
  const inventedEvidenceCheckFailed = inventedChecks.some(
    (check) => check.name === 'evidence references are grounded' && check.status === 'fail',
  )

  return summarizeSuite('controller-explanation-fixtures', [
    expectTrue(
      'grounded fixture passes',
      groundedChecks.every((check) => check.status === 'pass'),
      'Known-good controller explanation fixture should pass all checks.',
    ),
    expectTrue(
      'invented evidence fixture fails grounding',
      inventedEvidenceCheckFailed,
      'Fixture with invented evidence id should fail grounding checks.',
    ),
  ])
}

function validateGrounding(response: ControllerExplanationResponse): EvaluationCheck[] {
  const actionIds = new Set(response.input.recommendedActions.map((action) => action.id))
  const evidenceIds = new Set(response.input.evidenceItems.map((evidence) => evidence.id))
  const knownEntityIds = getKnownEntityIds(response.input)
  const referencedActionIds = response.explanation.recommendedActions.map((action) => action.actionId)
  const referencedEvidenceIds = response.explanation.evidenceBasis.map((evidence) => evidence.evidenceId)
  const textReferencedIds = extractEntityLikeIds(JSON.stringify(response.explanation))
  const unknownTextIds = textReferencedIds.filter((id) => !knownEntityIds.has(id))

  return [
    expectTrue(
      'action references are grounded',
      referencedActionIds.every((actionId) => actionIds.has(actionId)),
      'Every explanation action must reference an existing deterministic action id.',
    ),
    expectTrue(
      'evidence references are grounded',
      referencedEvidenceIds.every((evidenceId) => evidenceIds.has(evidenceId)),
      'Every evidence basis item must reference existing evidence.',
    ),
    expectTrue(
      'entity-like ids in text are grounded',
      unknownTextIds.length === 0,
      'Narrative text must not introduce unknown entity identifiers.',
    ),
  ]
}

function validateDecisionBoundary(response: ControllerExplanationResponse): EvaluationCheck[] {
  const explanationText = JSON.stringify(response.explanation).toLowerCase()
  const forbiddenTerm = boundaryTerms.find((term) => explanationText.includes(term))

  return [
    expectTrue(
      'explanation does not decide controlled fields',
      !forbiddenTerm,
      'Explanation must not claim to change readiness, risk, approval requirement, or rerun safety.',
    ),
    expectEqual(
      'deterministic readiness remains input-owned',
      response.input.riskAssessment.createdBy,
      'deterministic_risk_service',
    ),
    expectTrue(
      'approval requirement remains deterministic',
      response.input.recommendedActions.some((action) => action.approvalRequired),
      'Approval requirements should be sourced from deterministic recommended actions.',
    ),
  ]
}

function getKnownEntityIds(input: ControllerExplanationInput): Set<string> {
  return new Set([
    input.scenario.id,
    input.closeTask.id,
    input.riskAssessment.id,
    ...input.blockers.failedJobs.map((job) => job.id),
    ...input.blockers.metadataIssues.map((issue) => issue.id),
    ...input.blockers.serviceDependencies.map((dependency) => dependency.id),
    ...input.incidents.map((incident) => incident.id),
    ...input.recommendedActions.map((action) => action.id),
    ...input.approvalRequests.map((approval) => approval.id),
    ...input.evidenceItems.map((evidence) => evidence.id),
    ...input.auditEvents.map((event) => event.id),
  ])
}

function extractEntityLikeIds(text: string): string[] {
  const matches = text.match(
    /\b(?:task|job|dep|inc|meta|ev|risk|action|approval|audit)-[a-z0-9-]+\b/g,
  )

  return Array.from(new Set(matches ?? []))
}
